# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json

kind: AIchorManifest
apiVersion: 0.2.1

builder:
  image: genrl-onboarding-callum-tilbury
  dockerfile: ./Dockerfile
  context: .

spec:
  operator: tf
  image: srmarl
  command: ./experiments/default_exp.sh

  types:
    Worker:
      count: 5
      resources:
        cpus: 4
        ramRatio: 6
