remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jemoji
title: Selective Reincarnation in Multi-Agent Reinforcement Learning
description: Oral Presentation at Reincarnating Reinforcement Learning ICLR 2023 Workshop