remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Selective Reincarnation in Multi-Agent Reinfocement Learning
description: Bookmark this to keep an eye on my project updates!